### ISSUE TITLE
如何搜索C参考

### ISSUE THREAD

**Issue by rgw5267** [cildhdi/Wox.Plugin.CppRef#1]

**Comment by ikkz** [comment]
在搜索 c 参考时使用类似 ```cr c sort``` 的命令，是否符合你的要求呢，或者有更好的格式也可以留言，我会尽快实现并发布到release。

**Comment by rgw5267** [comment]
暂时没有想到更好的，我在“网页搜索”中自建了一个。
另外，是否方便给https://devdocs.io 建个插件

**Comment by ikkz** [comment]
``` https://devdocs.io ```似乎是输入时在本地使用 js 匹配结果，另外通过调试没有发现其他的搜索接口，并且在插件里实现设置 Preferences 也比较麻烦，可以考虑在网页搜索中添加```https://devdocs.io/#q={q}``` 。或者你有发现其他的实现方式也可以交流一下 @rgw5267

**Comment by rgw5267** [comment]
`https://devdocs.io/#q={q}`可以满足需求

**Comment by ikkz** [comment]
刚发的 [3.0.0](https://github.com/cildhdi/Wox.Plugin.CppRef/releases/tag/v3.0.0) 可以设置语言和 c/cpp 了，具体用法在 [README](https://github.com/cildhdi/Wox.Plugin.CppRef)。
